package PetProject.Menu;

public enum MenuButton {
    ADD_PEOPLE_BUTTON_1,
    ADD_UNIVERSITY_BUTTON_2,
    ADD_HOSTEL_BUTTON_3,
    SORT_BUTTON_4,
    GET_INFO_ABOUT_STUDENTS_BUTTON_5,
    GET_INFO_ABOUT_UNIVERSITIES_BUTTON_6,
    GET_INFO_ABOUT_HOSTEL_BUTTON_7,
    EXIT_BUTTON_8


}
